### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by bigkun** [WeBankFinTech/WeBASE#114]
$ python3 deploy.py installAll

`
============== WeBASE-Node-Manager  start...  ==============
Traceback (most recent call last):
  File "deploy.py", line 106, in <module>
    do()
  File "deploy.py", line 25, in do
    commBuild.do()
  File "/home/vagrant/webase1.4.1/webase-deploy/comm/build.py", line 18, in do
    installManager()
  File "/home/vagrant/webase1.4.1/webase-deploy/comm/build.py", line 376, in installManager
    startManager()
  File "/home/vagrant/webase1.4.1/webase-deploy/comm/build.py", line 388, in startManager
    result = doCmd("bash start.sh")
  File "/home/vagrant/webase1.4.1/webase-deploy/comm/utils.py", line 107, in doCmd
    raise Exception("execute cmd  error ,cmd : {}, status is {} ,output is {}".format(cmd,status, output))
Exception: execute cmd  error ,cmd : bash start.sh, status is 2 ,output is start.sh: line 2: $'\r': command not found
start.sh: line 9: $'\r': command not found
cat: /home/vagrant/webase1.4.1/webase-deploy/webase-node-mgr/
conf
/application.yml: No such file or directory
start.sh: line 21: syntax error near unexpected token `$'{\r''
start.sh: line 21: `copyArial(){
'
`

**Comment by bigkun** [comment]
安装dos2unix 把 stop.sh 和start.sh 脚本转换下格式
