### ISSUE TITLE
一键部署webfront启动失败，证书错误

### ISSUE THREAD

**Issue by wcmolin** [WeBankFinTech/WeBASE#117]
参考[文档-一键部署](https://webasedoc.readthedocs.io/zh_CN/latest/docs/WeBASE/install.html)
执行命令：
```
python deploy.py installAll
```
最后一段输出，提示初始化 Front 失败：
```
==============     WeBASE-Front     start...  ==============
=======     WeBASE-Front    starting .  Please check through the log file (default path:./webase-front/log/).    =======
==============     WeBASE-Front     end...    ==============
================================================================
==============  Init Front for Mgr start...   ==============
=============== Init Front for Mgr fail.      ==============
=====================    deploy   end...   =====================
=====================    webase-web version  v1.4.1        ==================
=====================    webase-node-mgr version  v1.4.1   ==================
=====================    webase-sign version  v1.4.1       ==================
=====================    webase-front version  v1.4.1      ==================
================================================================
```

`webfront` 启动失败，查看 `webfront/log/web3sdk.log`, 错误内容如下：
```

2020-11-27 11:23:20.814 [main] INFO  ChannelConnections() -  all connections: [ConnectionInfo{host='192.168.10.74', port=20200}]
2020-11-27 11:23:20.890 [main] INFO  ChannelConnections() -  ca certificate: ca.crt, sdk certificate: node.crt, sdk key: node.key
2020-11-27 11:23:21.788 [nioEventLoopGroup-2-1] ERROR ChannelHandler() -  handshake failed, host: 192.168.10.74, port: 20200, message: General OpenSslEngine problem, cause: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
2020-11-27 11:23:21.791 [nioEventLoopGroup-2-1] INFO  ChannelHandler() -  ssl close completion event, host: 192.168.10.74, port: 20200, ctx: 232020670
2020-11-27 11:23:21.794 [main] ERROR ChannelConnections() -  all connections have failed, [ ssl handshake failed:/192.168.10.74:20200, The reasons for failure may be: 1. the configured certificate is not the same set of certificates as the node's certificate; 2. the configured certificate is not issued by the same authority as the node's certificate. Please refer to https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk.html#id24]
2020-11-27 11:23:21.795 [main] ERROR Service() -  service init failed, error message:  Failed to connect to nodes: [ ssl handshake failed:/192.168.10.74:20200, The reasons for failure may be: 1. the configured certificate is not the same set of certificates as the node's certificate; 2. the configured certificate is not issued by the same authority as the node's certificate. Please refer to https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk.html#id24], error:
java.lang.RuntimeException:  Failed to connect to nodes: [ ssl handshake failed:/192.168.10.74:20200, The reasons for failure may be: 1. the configured certificate is not the same set of certificates as the node's certificate; 2. the configured certificate is not issued by the same authority as the node's certificate. Please refer to https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk.html#id24]
	at org.fisco.bcos.channel.handler.ChannelConnections.startConnect(ChannelConnections.java:490) ~[web3sdk-2.6.1.jar:?]
	at org.fisco.bcos.channel.client.Service.run(Service.java:335) [web3sdk-2.6.1.jar:?]
	at com.webank.webase.front.base.config.Web3Config.getWeb3j(Web3Config.java:116) [WeBASE-Front-upstream.jar:?]
	at com.webank.webase.front.base.config.Web3Config$$EnhancerBySpringCGLIB$$d7773ad8.CGLIB$getWeb3j$8(<generated>) [WeBASE-Front-upstream.jar:?]
```

**Comment by wcmolin** [comment]
问题已解决，参考这 [issue](https://github.com/WeBankFinTech/WeBASE-Front/issues/456#issuecomment-729607405)
