### ISSUE TITLE
根据文档进行一键Docker部署，节点管理服务和签名服务以及数据库容器无法正常启动，WeBASE管理平台进去显示“系统错误”

### ISSUE THREAD

**Issue by chienninglee** [WeBankFinTech/WeBASE#317]
common.properties文件的配置我只修改了nodecount为4，其余没有作修改。

`[root@VM-28-5-centos webase-deploy]# docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS          PORTS     NAMES
60440787a807   webasepro/webase-web:v1.5.5     "/wait-for-it.sh 127…"   37 minutes ago   Up 37 minutes             webase-web-5000
bc39fc325b0e   webasepro/webase-front:v1.5.5   "/wait-for-it.sh 127…"   37 minutes ago   Up 37 minutes             webase-front-5002
d770142f9cc9   fiscoorg/fiscobcos:v2.11.0      "/usr/local/bin/fisc…"   37 minutes ago   Up 37 minutes             rootwebase-deploynodes127.0.0.1node3
4cb8e3ff5b61   fiscoorg/fiscobcos:v2.11.0      "/usr/local/bin/fisc…"   37 minutes ago   Up 37 minutes             rootwebase-deploynodes127.0.0.1node0
37834134c015   fiscoorg/fiscobcos:v2.11.0      "/usr/local/bin/fisc…"   37 minutes ago   Up 37 minutes             rootwebase-deploynodes127.0.0.1node2
96736ed7fd62   fiscoorg/fiscobcos:v2.11.0      "/usr/local/bin/fisc…"   37 minutes ago   Up 37 minutes             rootwebase-deploynodes127.0.0.1node1
[root@VM-28-5-centos webase-deploy]# 
`
webase-node-manager的容器、签名服务webase-sign的容器、数据库容器端口未被监听，同时服务也自动关闭了。
尝试过手动启动这三个容器，依然会自动关闭。

![image](https://github.com/user-attachments/assets/d8cbe5ed-999a-40d9-9e27-50f41d0454d9)
管理平台后台页面显示系统错误，同时验证码也无法显示。
![image](https://github.com/user-attachments/assets/d8cbe5ed-999a-40d9-9e27-50f41d0454d9)

[WeBASE-Node-Manager-error [4].log](https://github.com/user-attachments/files/17610229/WeBASE-Node-Manager-error.4.log)
[WeBASE-Sign.log](https://github.com/user-attachments/files/17610230/WeBASE-Sign.log)

/root/webase-deploy/webase-sign/log/**WeBASE-Sign.log**：日志开头的部分内容
`2024-11-03 18:07:35.790 [background-preinit] INFO  Version() - HV000001: Hibernate Validator 6.2.5.Final
2024-11-03 18:07:36.026 [main] INFO  Application() - Starting Application using Java 1.8.0_362 on VM-28-5-centos with PID 52 (/dist/apps/WeBASE-Sign.jar started by root in /dist)
2024-11-03 18:07:36.046 [main] INFO  Application() - The following 1 profile is active: "docker"
2024-11-03 18:07:57.503 [main] INFO  TomcatWebServer() - Tomcat initialized with port(s): 5004 (http)
2024-11-03 18:07:59.027 [main] INFO  ServletWebServerApplicationContext() - Root WebApplicationContext: initialization completed in 22659 ms
2024-11-03 18:08:02.240 [main] INFO  HikariDataSource() - HikariPool-1 - Starting...
2024-11-03 18:08:03.696 [main] ERROR HikariPool() - HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.`

/root/webase-deploy/webase-node-mgr/log/**WeBASE-Node-Manager-error.log**：日志开头的部分内容：
`[ERROR][2024-11-03 18:08:17.243][node-mgr-task-3][wsweb][2224][2224][LOG_POINT]HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.22.jar:8.0.22]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.22.jar:8.0.22]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836) ~[mysql-connector-java-8.0.22.jar:8.0.22]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.22.jar:8.0.22]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.22.jar:8.0.22]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.22.jar:8.0.22]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-3.4.5.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[HikariCP-3.4.5.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-3.4.5.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[HikariCP-3.4.5.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[HikariCP-3.4.5.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-3.4.5.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-3.4.5.jar:?]
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:265) ~[spring-jdbc-5.3.1.jar:5.3.1]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400) ~[spring-tx-5.3.1.jar:5.3.1]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-5.3.1.jar:5.3.1]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:578) ~[spring-tx-5.3.1.jar:5.3.1]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:365) ~[spring-tx-5.3.1.jar:5.3.1]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:134) ~[spring-tx-5.3.1.jar:5.3.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.26.jar:5.3.26]
	at com.webank.webase.node.mgr.group.GroupService$$EnhancerBySpringCGLIB$$b9027e05.resetGroupList(<generated>) ~[WeBASE-Node-Manager.jar:?]
	at com.webank.webase.node.mgr.scheduler.ResetGroupListTask.resetGroupList(ResetGroupListTask.java:64) ~[WeBASE-Node-Manager.jar:?]
	at com.webank.webase.node.mgr.scheduler.ResetGroupListTask.taskStart(ResetGroupListTask.java:40) ~[WeBASE-Node-Manager.jar:?]
	at com.webank.webase.node.mgr.scheduler.ResetGroupListTask$$FastClassBySpringCGLIB$$346d19f0.invoke(<generated>) ~[WeBASE-Node-Manager.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.26.jar:5.3.26]
	at com.webank.webase.node.mgr.scheduler.ResetGroupListTask$$EnhancerBySpringCGLIB$$e391be6c.taskStart(<generated>) ~[WeBASE-Node-Manager.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.26.jar:5.3.26]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_362]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_362]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_362]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure`

**Comment by chienninglee** [comment]
![image](https://github.com/user-attachments/assets/60261e19-0e3e-4088-9e7a-da3439cf7831)

**Comment by chienninglee** [comment]
停止一键部署的所有服务    python3 deploy.py stopDockerAll
启动一键部署的所有服务    python3 deploy.py startDockerAll
根据以上命令重启服务也无济于事

**Comment by CodingCattwo** [comment]
看日志报错事jdbc的connection异常，也就是服务无法连上db；需要检查你配置文件中的db的ip port和密码是否正确。
